#!/usr/bin/env bash

username="$USER"
fixedtn='no'

while getopts 'un:h' opt; do
  case "$opt" in
    n)
      fixedtn="$OPTARG"
      ;;

    ?|h)
      echo "Usage: $(basename $0) [-n transfer number]"
      exit 1
      ;;
  esac
done
shift "$(($OPTIND -1))"
userhome=$(eval echo ~"$username")

# get a list of current sessions
active_sessions=($(screen -ls | grep -o 'drsync\.[0-9]*'))

if [[ "$fixedtn" == 'no' ]]; then
  for session in "${active_sessions[@]}"
  do
    logfile=$(echo "$userhome"/.drsync_transfers/"$session".status)
    if [ -f "$logfile" ]; then
      echo "========> $logfile <========"
      sed -e '/^$/d' "$logfile"
      echo ''
    fi
  done
else
  session_name=`printf 'drsync.%06g' "$fixedtn"`
  logfile=$(eval echo ~"$username"/.drsync_transfers/"$session_name".status)
  echo "========> $logfile <========"
  sed -e '/^$/d' "$logfile"
fi
