#!/usr/bin/env bash

username="$USER"
fixedtn='no'

while getopts 'u:n:h' o; do
  case "${o}" in
    u)
      username="$OPTARG"
      ;;

    n)
      fixedtn="$OPTARG"
      ;;

    ?|h)
      echo "Usage: $(basename $0) [-n transfer number]"
      echo "Usage: $(basename $0) [-u username]"
      exit 1
      ;;
  esac
done
shift "$(($OPTIND -1))"
userhome=$(eval echo ~"$username")
socketsdir=$(screen -ls | grep -o '/.*/' | sort | uniq)

# get a list of current sessions for the selected user
active_sessions=($(find "$socketsdir" -iregex ".*$username.*" | grep -o 'drsync\.[0-9]*'))

if [[ "$fixedtn" == 'no' ]]; then
  for session in "${active_sessions[@]}"
  do
    logfile=$(echo "$userhome"/.drsync_transfers/"$session".status)
    if [ -f "$logfile" ]; then
      echo "========> $logfile <========"
      sed -e '/^$/d' "$logfile"
      echo ''
    fi
  done
else
  session=`printf 'drsync.%06g' "$fixedtn"`
  logfile=$(eval echo ~"$username"/.drsync_transfers/"$session".status)
  echo "========> $logfile <========"
  sed -e '/^$/d' "$logfile"
fi
